### ISSUE TITLE
When new content has been mapped to the Canonical Structure, I want to save it to the Content Repository so it can be retrieved as needed

### ISSUE THREAD

**Issue by eevans** [wikimedia/phoenix#5]
Content that has been mapped to the Canonical Structure will need to be stored in the Content Repository, and indexed accordingly.

- [x] JSON serializable structs: #6 
- [x] Content storage abstraction: #10
- [ ] Indexing for lookups: #13
