### ISSUE TITLE
One-time full-corpus import with Rosette service restraints

### ISSUE THREAD

**Issue by eevans** [wikimedia/phoenix#91]
The Po[CV] will be demoed with a complete dataset from [simple.wikipedia.org](https://simple.wikipedia.org) (180,029 articles at the time of this writing).  Afterward, [a small set of documents](https://github.com/wikimedia/phoenix/blob/master/lambdas/related-topics/allowlist.go) will be selected for continuous update.

The challenge with this will the constraints imposed by [Rosette](https://www.rosette.com).  Using the [large offering](https://www.rosette.com/pricing/), we are limited to 500,000 calls in a month, 80,000 in day, and a concurrency of 1; Processing will need to be synchronous and rate-limited to no more than 55 sections per minute.  Since we have an estimated 469,560 nodes, there is a) no room for error (having to restart the import after making any significant process will leave us short), and b) we are limited to ~30,000 requests over the remaining monthly period for updates to allowlisted documents.

Since this is a one-time effort, and since it is antithetical to the Phoenix system architecture, the proposed approach is to tackle this in an ad hoc fashion, external to the AWS environment.  We we will use a scan of the `scpoc-dynamodb-node-names` DynamoDB table (after a complete/verified, full import), and suite of locally run utilities to semi-manually establish this import.

## Tasks

- [x] Make it possible to disable the outgoing (aka _node published_) events from the `transform-parsoid` Lambda
- [x] Perform a complete import (with related topic processing off) to establish a trustworthy (and up-to-date) list of all nodes
- [x] Move application of the allowlist from [related-topics](https://github.com/wikimedia/phoenix/blob/master/lambdas/related-topics) (where it applies only to the storage & indexing of topics) to events generated by the Wikimedia Event Streams service

**Comment by eevans** [comment]
Complete
